#############################################
#constant values used throughout the program#
#############################################
WORLDSIZE = 1000
SPAWNBORDER = 50

UP = 0
DOWN = 180
LEFT = 90
RIGHT = 270

MOVE = 1
TURNLEFT = 2
TURNRIGHT = 3

#menu universal
FPS = 990
FOODENERGY = 100

#menu Train Predators
PTRAINFOODCOUNT = 40
PTRAINGENERATIONS = 500

#menu Train Herbivores
HTRAINGENERATIONS = 500
HTRAINFOODCOUNT = 40
HTRAINPREDATORCOUNT = 20
HTRAINPREDATORMOVE = True

#menu Run Planet
POPULATION = 75
FOODRESPAWN = 10
FOODDENSITY = 20
FOODCLUMPSIZE = 9
HREPRODUCTIONTHRESHOLD = 2000
PREPRODUCTIONTHRESHOLD = 7000

#Run Planet GA
VIEWDISTANCEMIN = 50
VIEWDISTANCEMAX = 500
SLEEPTIMEMIN = 100
SLEEPTIMEMAX = 500
METABOLISMMIN = 1
METABOLISMMAX = 9